// Curated list of common US-listed tickers. Serves two purposes:
//   1. Autocomplete suggestions on the add-holding form.
//   2. Skipping the Massive API call entirely when the submitted ticker is
//      in this list — domicile/currency are hardcoded here instead of
//      fetched, since every entry is NYSE/NASDAQ/ARCX-listed (including the
//      foreign ADRs), which is exactly what Massive's own
//      exchange-based domicile guess would already produce (see
//      exchange-domicile.ts) — so this is a free win, not a shortcut that
//      changes behavior.
// It is NOT the source of truth for what's actually supported — a ticker
// missing from this list still gets validated against Massive when
// submitted (see addHolding in dashboard/actions.ts); one that's listed
// here can still turn out to be unsupported if Massive doesn't cover it.
export interface KnownTicker {
  ticker: string;
  name: string;
  domicile: string;
  currency: string;
}

export const KNOWN_TICKERS: KnownTicker[] = [
  { ticker: "AAPL", name: "Apple Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MSFT", name: "Microsoft Corp.", domicile: "USA", currency: "USD" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)", domicile: "USA", currency: "USD" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)", domicile: "USA", currency: "USD" },
  { ticker: "AMZN", name: "Amazon.com Inc.", domicile: "USA", currency: "USD" },
  { ticker: "META", name: "Meta Platforms Inc.", domicile: "USA", currency: "USD" },
  { ticker: "NVDA", name: "NVIDIA Corp.", domicile: "USA", currency: "USD" },
  { ticker: "TSLA", name: "Tesla Inc.", domicile: "USA", currency: "USD" },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)", domicile: "USA", currency: "USD" },
  { ticker: "AVGO", name: "Broadcom Inc.", domicile: "USA", currency: "USD" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", domicile: "USA", currency: "USD" },
  { ticker: "V", name: "Visa Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MA", name: "Mastercard Inc.", domicile: "USA", currency: "USD" },
  { ticker: "UNH", name: "UnitedHealth Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "HD", name: "Home Depot Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PG", name: "Procter & Gamble Co.", domicile: "USA", currency: "USD" },
  { ticker: "JNJ", name: "Johnson & Johnson", domicile: "USA", currency: "USD" },
  { ticker: "KO", name: "Coca-Cola Co.", domicile: "USA", currency: "USD" },
  { ticker: "PEP", name: "PepsiCo Inc.", domicile: "USA", currency: "USD" },
  { ticker: "COST", name: "Costco Wholesale Corp.", domicile: "USA", currency: "USD" },
  { ticker: "WMT", name: "Walmart Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MRK", name: "Merck & Co.", domicile: "USA", currency: "USD" },
  { ticker: "ABBV", name: "AbbVie Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PFE", name: "Pfizer Inc.", domicile: "USA", currency: "USD" },
  { ticker: "LLY", name: "Eli Lilly and Co.", domicile: "USA", currency: "USD" },
  { ticker: "BAC", name: "Bank of America Corp.", domicile: "USA", currency: "USD" },
  { ticker: "WFC", name: "Wells Fargo & Co.", domicile: "USA", currency: "USD" },
  { ticker: "GS", name: "Goldman Sachs Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MS", name: "Morgan Stanley", domicile: "USA", currency: "USD" },
  { ticker: "C", name: "Citigroup Inc.", domicile: "USA", currency: "USD" },
  { ticker: "XOM", name: "Exxon Mobil Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CVX", name: "Chevron Corp.", domicile: "USA", currency: "USD" },
  { ticker: "COP", name: "ConocoPhillips", domicile: "USA", currency: "USD" },
  { ticker: "SLB", name: "Schlumberger Ltd.", domicile: "USA", currency: "USD" },
  { ticker: "T", name: "AT&T Inc.", domicile: "USA", currency: "USD" },
  { ticker: "VZ", name: "Verizon Communications Inc.", domicile: "USA", currency: "USD" },
  { ticker: "TMUS", name: "T-Mobile US Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DIS", name: "Walt Disney Co.", domicile: "USA", currency: "USD" },
  { ticker: "NFLX", name: "Netflix Inc.", domicile: "USA", currency: "USD" },
  { ticker: "CMCSA", name: "Comcast Corp.", domicile: "USA", currency: "USD" },
  { ticker: "INTC", name: "Intel Corp.", domicile: "USA", currency: "USD" },
  { ticker: "AMD", name: "Advanced Micro Devices Inc.", domicile: "USA", currency: "USD" },
  { ticker: "CSCO", name: "Cisco Systems Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ORCL", name: "Oracle Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CRM", name: "Salesforce Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ADBE", name: "Adobe Inc.", domicile: "USA", currency: "USD" },
  { ticker: "IBM", name: "International Business Machines Corp.", domicile: "USA", currency: "USD" },
  { ticker: "QCOM", name: "Qualcomm Inc.", domicile: "USA", currency: "USD" },
  { ticker: "TXN", name: "Texas Instruments Inc.", domicile: "USA", currency: "USD" },
  { ticker: "NOW", name: "ServiceNow Inc.", domicile: "USA", currency: "USD" },
  { ticker: "AMAT", name: "Applied Materials Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MU", name: "Micron Technology Inc.", domicile: "USA", currency: "USD" },
  { ticker: "UBER", name: "Uber Technologies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ABT", name: "Abbott Laboratories", domicile: "USA", currency: "USD" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DHR", name: "Danaher Corp.", domicile: "USA", currency: "USD" },
  { ticker: "MDT", name: "Medtronic plc", domicile: "USA", currency: "USD" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Co.", domicile: "USA", currency: "USD" },
  { ticker: "AMGN", name: "Amgen Inc.", domicile: "USA", currency: "USD" },
  { ticker: "GILD", name: "Gilead Sciences Inc.", domicile: "USA", currency: "USD" },
  { ticker: "CVS", name: "CVS Health Corp.", domicile: "USA", currency: "USD" },
  { ticker: "MCD", name: "McDonald's Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SBUX", name: "Starbucks Corp.", domicile: "USA", currency: "USD" },
  { ticker: "NKE", name: "Nike Inc.", domicile: "USA", currency: "USD" },
  { ticker: "LOW", name: "Lowe's Companies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "TGT", name: "Target Corp.", domicile: "USA", currency: "USD" },
  { ticker: "TJX", name: "TJX Companies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "BKNG", name: "Booking Holdings Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MMM", name: "3M Co.", domicile: "USA", currency: "USD" },
  { ticker: "HON", name: "Honeywell International Inc.", domicile: "USA", currency: "USD" },
  { ticker: "CAT", name: "Caterpillar Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DE", name: "Deere & Co.", domicile: "USA", currency: "USD" },
  { ticker: "GE", name: "General Electric Co.", domicile: "USA", currency: "USD" },
  { ticker: "BA", name: "Boeing Co.", domicile: "USA", currency: "USD" },
  { ticker: "LMT", name: "Lockheed Martin Corp.", domicile: "USA", currency: "USD" },
  { ticker: "RTX", name: "RTX Corp.", domicile: "USA", currency: "USD" },
  { ticker: "NOC", name: "Northrop Grumman Corp.", domicile: "USA", currency: "USD" },
  { ticker: "UPS", name: "United Parcel Service Inc.", domicile: "USA", currency: "USD" },
  { ticker: "FDX", name: "FedEx Corp.", domicile: "USA", currency: "USD" },
  { ticker: "UNP", name: "Union Pacific Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CSX", name: "CSX Corp.", domicile: "USA", currency: "USD" },
  { ticker: "NEE", name: "NextEra Energy Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DUK", name: "Duke Energy Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SO", name: "Southern Co.", domicile: "USA", currency: "USD" },
  { ticker: "D", name: "Dominion Energy Inc.", domicile: "USA", currency: "USD" },
  { ticker: "AEP", name: "American Electric Power Co.", domicile: "USA", currency: "USD" },
  { ticker: "EXC", name: "Exelon Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SRE", name: "Sempra", domicile: "USA", currency: "USD" },
  { ticker: "PLD", name: "Prologis Inc.", domicile: "USA", currency: "USD" },
  { ticker: "AMT", name: "American Tower Corp.", domicile: "USA", currency: "USD" },
  { ticker: "O", name: "Realty Income Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SPG", name: "Simon Property Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PSA", name: "Public Storage", domicile: "USA", currency: "USD" },
  { ticker: "MAIN", name: "Main Street Capital Corp.", domicile: "USA", currency: "USD" },
  { ticker: "ARCC", name: "Ares Capital Corp.", domicile: "USA", currency: "USD" },
  { ticker: "STAG", name: "STAG Industrial Inc.", domicile: "USA", currency: "USD" },
  { ticker: "VICI", name: "VICI Properties Inc.", domicile: "USA", currency: "USD" },
  { ticker: "WPC", name: "W. P. Carey Inc.", domicile: "USA", currency: "USD" },
  { ticker: "SCHW", name: "Charles Schwab Corp.", domicile: "USA", currency: "USD" },
  { ticker: "BLK", name: "BlackRock Inc.", domicile: "USA", currency: "USD" },
  { ticker: "SPGI", name: "S&P Global Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ICE", name: "Intercontinental Exchange Inc.", domicile: "USA", currency: "USD" },
  { ticker: "CME", name: "CME Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "AXP", name: "American Express Co.", domicile: "USA", currency: "USD" },
  { ticker: "COF", name: "Capital One Financial Corp.", domicile: "USA", currency: "USD" },
  { ticker: "USB", name: "U.S. Bancorp", domicile: "USA", currency: "USD" },
  { ticker: "PNC", name: "PNC Financial Services Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "TFC", name: "Truist Financial Corp.", domicile: "USA", currency: "USD" },
  { ticker: "MET", name: "MetLife Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PRU", name: "Prudential Financial Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ALL", name: "Allstate Corp.", domicile: "USA", currency: "USD" },
  { ticker: "TRV", name: "Travelers Companies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PGR", name: "Progressive Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CB", name: "Chubb Ltd.", domicile: "USA", currency: "USD" },
  { ticker: "AIG", name: "American International Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "F", name: "Ford Motor Co.", domicile: "USA", currency: "USD" },
  { ticker: "GM", name: "General Motors Co.", domicile: "USA", currency: "USD" },
  { ticker: "KMB", name: "Kimberly-Clark Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CL", name: "Colgate-Palmolive Co.", domicile: "USA", currency: "USD" },
  { ticker: "GIS", name: "General Mills Inc.", domicile: "USA", currency: "USD" },
  { ticker: "K", name: "Kellanova", domicile: "USA", currency: "USD" },
  { ticker: "MDLZ", name: "Mondelez International Inc.", domicile: "USA", currency: "USD" },
  { ticker: "MO", name: "Altria Group Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PM", name: "Philip Morris International Inc.", domicile: "USA", currency: "USD" },
  { ticker: "STZ", name: "Constellation Brands Inc.", domicile: "USA", currency: "USD" },
  { ticker: "KHC", name: "Kraft Heinz Co.", domicile: "USA", currency: "USD" },
  { ticker: "HSY", name: "Hershey Co.", domicile: "USA", currency: "USD" },
  { ticker: "SYY", name: "Sysco Corp.", domicile: "USA", currency: "USD" },
  { ticker: "ADM", name: "Archer-Daniels-Midland Co.", domicile: "USA", currency: "USD" },
  { ticker: "KMI", name: "Kinder Morgan Inc.", domicile: "USA", currency: "USD" },
  { ticker: "WMB", name: "Williams Companies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "OKE", name: "ONEOK Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PSX", name: "Phillips 66", domicile: "USA", currency: "USD" },
  { ticker: "MPC", name: "Marathon Petroleum Corp.", domicile: "USA", currency: "USD" },
  { ticker: "VLO", name: "Valero Energy Corp.", domicile: "USA", currency: "USD" },
  { ticker: "EOG", name: "EOG Resources Inc.", domicile: "USA", currency: "USD" },
  { ticker: "OXY", name: "Occidental Petroleum Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SHEL", name: "Shell plc", domicile: "USA", currency: "USD" },
  { ticker: "BP", name: "BP plc", domicile: "USA", currency: "USD" },
  { ticker: "TTE", name: "TotalEnergies SE", domicile: "USA", currency: "USD" },
  { ticker: "UL", name: "Unilever plc", domicile: "USA", currency: "USD" },
  { ticker: "NVS", name: "Novartis AG", domicile: "USA", currency: "USD" },
  { ticker: "AZN", name: "AstraZeneca plc", domicile: "USA", currency: "USD" },
  { ticker: "SAP", name: "SAP SE", domicile: "USA", currency: "USD" },
  { ticker: "TM", name: "Toyota Motor Corp.", domicile: "USA", currency: "USD" },
  { ticker: "SONY", name: "Sony Group Corp.", domicile: "USA", currency: "USD" },
  { ticker: "ASML", name: "ASML Holding N.V.", domicile: "USA", currency: "USD" },
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing Co.", domicile: "USA", currency: "USD" },
  { ticker: "BABA", name: "Alibaba Group Holding Ltd.", domicile: "USA", currency: "USD" },
  { ticker: "HSBC", name: "HSBC Holdings plc", domicile: "USA", currency: "USD" },
  { ticker: "DEO", name: "Diageo plc", domicile: "USA", currency: "USD" },
  { ticker: "BTI", name: "British American Tobacco plc", domicile: "USA", currency: "USD" },
  { ticker: "RIO", name: "Rio Tinto plc", domicile: "USA", currency: "USD" },
  { ticker: "VALE", name: "Vale S.A.", domicile: "USA", currency: "USD" },
  { ticker: "ET", name: "Energy Transfer LP", domicile: "USA", currency: "USD" },
  { ticker: "EPD", name: "Enterprise Products Partners LP", domicile: "USA", currency: "USD" },
  { ticker: "MPLX", name: "MPLX LP", domicile: "USA", currency: "USD" },
  { ticker: "PAA", name: "Plains All American Pipeline LP", domicile: "USA", currency: "USD" },
  { ticker: "ADP", name: "Automatic Data Processing Inc.", domicile: "USA", currency: "USD" },
  { ticker: "PAYX", name: "Paychex Inc.", domicile: "USA", currency: "USD" },
  { ticker: "FIS", name: "Fidelity National Information Services Inc.", domicile: "USA", currency: "USD" },
  { ticker: "FISV", name: "Fiserv Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ROP", name: "Roper Technologies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ITW", name: "Illinois Tool Works Inc.", domicile: "USA", currency: "USD" },
  { ticker: "EMR", name: "Emerson Electric Co.", domicile: "USA", currency: "USD" },
  { ticker: "ETN", name: "Eaton Corp. plc", domicile: "USA", currency: "USD" },
  { ticker: "PH", name: "Parker Hannifin Corp.", domicile: "USA", currency: "USD" },
  { ticker: "CMI", name: "Cummins Inc.", domicile: "USA", currency: "USD" },
  { ticker: "GD", name: "General Dynamics Corp.", domicile: "USA", currency: "USD" },
  { ticker: "LHX", name: "L3Harris Technologies Inc.", domicile: "USA", currency: "USD" },
  { ticker: "WM", name: "Waste Management Inc.", domicile: "USA", currency: "USD" },
  { ticker: "RSG", name: "Republic Services Inc.", domicile: "USA", currency: "USD" },
  { ticker: "ECL", name: "Ecolab Inc.", domicile: "USA", currency: "USD" },
  { ticker: "LIN", name: "Linde plc", domicile: "USA", currency: "USD" },
  { ticker: "APD", name: "Air Products and Chemicals Inc.", domicile: "USA", currency: "USD" },
  { ticker: "SHW", name: "Sherwin-Williams Co.", domicile: "USA", currency: "USD" },
  { ticker: "NEM", name: "Newmont Corp.", domicile: "USA", currency: "USD" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DOW", name: "Dow Inc.", domicile: "USA", currency: "USD" },
  { ticker: "DD", name: "DuPont de Nemours Inc.", domicile: "USA", currency: "USD" },
  { ticker: "LYB", name: "LyondellBasell Industries N.V.", domicile: "USA", currency: "USD" },
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust", domicile: "USA", currency: "USD" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", domicile: "USA", currency: "USD" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF", domicile: "USA", currency: "USD" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", domicile: "USA", currency: "USD" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF", domicile: "USA", currency: "USD" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF", domicile: "USA", currency: "USD" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF", domicile: "USA", currency: "USD" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF", domicile: "USA", currency: "USD" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF", domicile: "USA", currency: "USD" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF", domicile: "USA", currency: "USD" },
  { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF", domicile: "USA", currency: "USD" },
  { ticker: "DGRO", name: "iShares Core Dividend Growth ETF", domicile: "USA", currency: "USD" },
  { ticker: "HDV", name: "iShares Core High Dividend ETF", domicile: "USA", currency: "USD" },
  { ticker: "SPYD", name: "SPDR Portfolio S&P 500 High Dividend ETF", domicile: "USA", currency: "USD" },
  { ticker: "SPHD", name: "Invesco S&P 500 High Div Low Volatility ETF", domicile: "USA", currency: "USD" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", domicile: "USA", currency: "USD" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF", domicile: "USA", currency: "USD" },
  { ticker: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF", domicile: "USA", currency: "USD" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF", domicile: "USA", currency: "USD" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF", domicile: "USA", currency: "USD" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLB", name: "Materials Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR Fund", domicile: "USA", currency: "USD" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF", domicile: "USA", currency: "USD" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF", domicile: "USA", currency: "USD" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF", domicile: "USA", currency: "USD" },
  { ticker: "GLD", name: "SPDR Gold Shares", domicile: "USA", currency: "USD" },
  { ticker: "SLV", name: "iShares Silver Trust", domicile: "USA", currency: "USD" },
];
