// Curated list of common US-listed tickers for autocomplete suggestions only.
// It is NOT the source of truth for what's actually supported — that's
// decided server-side by Massive when the holding is submitted (see
// addHolding in dashboard/actions.ts). A ticker missing from this list can
// still be typed and submitted manually; one that's listed here can still
// turn out to be unsupported if Massive doesn't cover it.
export interface KnownTicker {
  ticker: string;
  name: string;
}

export const KNOWN_TICKERS: KnownTicker[] = [
  { ticker: "AAPL", name: "Apple Inc." },
  { ticker: "MSFT", name: "Microsoft Corp." },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)" },
  { ticker: "AMZN", name: "Amazon.com Inc." },
  { ticker: "META", name: "Meta Platforms Inc." },
  { ticker: "NVDA", name: "NVIDIA Corp." },
  { ticker: "TSLA", name: "Tesla Inc." },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)" },
  { ticker: "AVGO", name: "Broadcom Inc." },
  { ticker: "JPM", name: "JPMorgan Chase & Co." },
  { ticker: "V", name: "Visa Inc." },
  { ticker: "MA", name: "Mastercard Inc." },
  { ticker: "UNH", name: "UnitedHealth Group Inc." },
  { ticker: "HD", name: "Home Depot Inc." },
  { ticker: "PG", name: "Procter & Gamble Co." },
  { ticker: "JNJ", name: "Johnson & Johnson" },
  { ticker: "KO", name: "Coca-Cola Co." },
  { ticker: "PEP", name: "PepsiCo Inc." },
  { ticker: "COST", name: "Costco Wholesale Corp." },
  { ticker: "WMT", name: "Walmart Inc." },
  { ticker: "MRK", name: "Merck & Co." },
  { ticker: "ABBV", name: "AbbVie Inc." },
  { ticker: "PFE", name: "Pfizer Inc." },
  { ticker: "LLY", name: "Eli Lilly and Co." },
  { ticker: "BAC", name: "Bank of America Corp." },
  { ticker: "WFC", name: "Wells Fargo & Co." },
  { ticker: "GS", name: "Goldman Sachs Group Inc." },
  { ticker: "MS", name: "Morgan Stanley" },
  { ticker: "C", name: "Citigroup Inc." },
  { ticker: "XOM", name: "Exxon Mobil Corp." },
  { ticker: "CVX", name: "Chevron Corp." },
  { ticker: "COP", name: "ConocoPhillips" },
  { ticker: "SLB", name: "Schlumberger Ltd." },
  { ticker: "T", name: "AT&T Inc." },
  { ticker: "VZ", name: "Verizon Communications Inc." },
  { ticker: "TMUS", name: "T-Mobile US Inc." },
  { ticker: "DIS", name: "Walt Disney Co." },
  { ticker: "NFLX", name: "Netflix Inc." },
  { ticker: "CMCSA", name: "Comcast Corp." },
  { ticker: "INTC", name: "Intel Corp." },
  { ticker: "AMD", name: "Advanced Micro Devices Inc." },
  { ticker: "CSCO", name: "Cisco Systems Inc." },
  { ticker: "ORCL", name: "Oracle Corp." },
  { ticker: "CRM", name: "Salesforce Inc." },
  { ticker: "ADBE", name: "Adobe Inc." },
  { ticker: "IBM", name: "International Business Machines Corp." },
  { ticker: "QCOM", name: "Qualcomm Inc." },
  { ticker: "TXN", name: "Texas Instruments Inc." },
  { ticker: "NOW", name: "ServiceNow Inc." },
  { ticker: "AMAT", name: "Applied Materials Inc." },
  { ticker: "MU", name: "Micron Technology Inc." },
  { ticker: "UBER", name: "Uber Technologies Inc." },
  { ticker: "PYPL", name: "PayPal Holdings Inc." },
  { ticker: "ABT", name: "Abbott Laboratories" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc." },
  { ticker: "DHR", name: "Danaher Corp." },
  { ticker: "MDT", name: "Medtronic plc" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Co." },
  { ticker: "AMGN", name: "Amgen Inc." },
  { ticker: "GILD", name: "Gilead Sciences Inc." },
  { ticker: "CVS", name: "CVS Health Corp." },
  { ticker: "MCD", name: "McDonald's Corp." },
  { ticker: "SBUX", name: "Starbucks Corp." },
  { ticker: "NKE", name: "Nike Inc." },
  { ticker: "LOW", name: "Lowe's Companies Inc." },
  { ticker: "TGT", name: "Target Corp." },
  { ticker: "TJX", name: "TJX Companies Inc." },
  { ticker: "BKNG", name: "Booking Holdings Inc." },
  { ticker: "MMM", name: "3M Co." },
  { ticker: "HON", name: "Honeywell International Inc." },
  { ticker: "CAT", name: "Caterpillar Inc." },
  { ticker: "DE", name: "Deere & Co." },
  { ticker: "GE", name: "General Electric Co." },
  { ticker: "BA", name: "Boeing Co." },
  { ticker: "LMT", name: "Lockheed Martin Corp." },
  { ticker: "RTX", name: "RTX Corp." },
  { ticker: "NOC", name: "Northrop Grumman Corp." },
  { ticker: "UPS", name: "United Parcel Service Inc." },
  { ticker: "FDX", name: "FedEx Corp." },
  { ticker: "UNP", name: "Union Pacific Corp." },
  { ticker: "CSX", name: "CSX Corp." },
  { ticker: "NEE", name: "NextEra Energy Inc." },
  { ticker: "DUK", name: "Duke Energy Corp." },
  { ticker: "SO", name: "Southern Co." },
  { ticker: "D", name: "Dominion Energy Inc." },
  { ticker: "AEP", name: "American Electric Power Co." },
  { ticker: "EXC", name: "Exelon Corp." },
  { ticker: "SRE", name: "Sempra" },
  { ticker: "PLD", name: "Prologis Inc." },
  { ticker: "AMT", name: "American Tower Corp." },
  { ticker: "O", name: "Realty Income Corp." },
  { ticker: "SPG", name: "Simon Property Group Inc." },
  { ticker: "PSA", name: "Public Storage" },
  { ticker: "MAIN", name: "Main Street Capital Corp." },
  { ticker: "ARCC", name: "Ares Capital Corp." },
  { ticker: "STAG", name: "STAG Industrial Inc." },
  { ticker: "VICI", name: "VICI Properties Inc." },
  { ticker: "WPC", name: "W. P. Carey Inc." },
  { ticker: "SCHW", name: "Charles Schwab Corp." },
  { ticker: "BLK", name: "BlackRock Inc." },
  { ticker: "SPGI", name: "S&P Global Inc." },
  { ticker: "ICE", name: "Intercontinental Exchange Inc." },
  { ticker: "CME", name: "CME Group Inc." },
  { ticker: "AXP", name: "American Express Co." },
  { ticker: "COF", name: "Capital One Financial Corp." },
  { ticker: "USB", name: "U.S. Bancorp" },
  { ticker: "PNC", name: "PNC Financial Services Group Inc." },
  { ticker: "TFC", name: "Truist Financial Corp." },
  { ticker: "MET", name: "MetLife Inc." },
  { ticker: "PRU", name: "Prudential Financial Inc." },
  { ticker: "ALL", name: "Allstate Corp." },
  { ticker: "TRV", name: "Travelers Companies Inc." },
  { ticker: "PGR", name: "Progressive Corp." },
  { ticker: "CB", name: "Chubb Ltd." },
  { ticker: "AIG", name: "American International Group Inc." },
  { ticker: "F", name: "Ford Motor Co." },
  { ticker: "GM", name: "General Motors Co." },
  { ticker: "KMB", name: "Kimberly-Clark Corp." },
  { ticker: "CL", name: "Colgate-Palmolive Co." },
  { ticker: "GIS", name: "General Mills Inc." },
  { ticker: "K", name: "Kellanova" },
  { ticker: "MDLZ", name: "Mondelez International Inc." },
  { ticker: "MO", name: "Altria Group Inc." },
  { ticker: "PM", name: "Philip Morris International Inc." },
  { ticker: "STZ", name: "Constellation Brands Inc." },
  { ticker: "KHC", name: "Kraft Heinz Co." },
  { ticker: "HSY", name: "Hershey Co." },
  { ticker: "SYY", name: "Sysco Corp." },
  { ticker: "ADM", name: "Archer-Daniels-Midland Co." },
  { ticker: "KMI", name: "Kinder Morgan Inc." },
  { ticker: "WMB", name: "Williams Companies Inc." },
  { ticker: "OKE", name: "ONEOK Inc." },
  { ticker: "PSX", name: "Phillips 66" },
  { ticker: "MPC", name: "Marathon Petroleum Corp." },
  { ticker: "VLO", name: "Valero Energy Corp." },
  { ticker: "EOG", name: "EOG Resources Inc." },
  { ticker: "OXY", name: "Occidental Petroleum Corp." },
  { ticker: "SHEL", name: "Shell plc" },
  { ticker: "BP", name: "BP plc" },
  { ticker: "TTE", name: "TotalEnergies SE" },
  { ticker: "UL", name: "Unilever plc" },
  { ticker: "NVS", name: "Novartis AG" },
  { ticker: "AZN", name: "AstraZeneca plc" },
  { ticker: "SAP", name: "SAP SE" },
  { ticker: "TM", name: "Toyota Motor Corp." },
  { ticker: "SONY", name: "Sony Group Corp." },
  { ticker: "ASML", name: "ASML Holding N.V." },
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing Co." },
  { ticker: "BABA", name: "Alibaba Group Holding Ltd." },
  { ticker: "HSBC", name: "HSBC Holdings plc" },
  { ticker: "DEO", name: "Diageo plc" },
  { ticker: "BTI", name: "British American Tobacco plc" },
  { ticker: "RIO", name: "Rio Tinto plc" },
  { ticker: "VALE", name: "Vale S.A." },
  { ticker: "ET", name: "Energy Transfer LP" },
  { ticker: "EPD", name: "Enterprise Products Partners LP" },
  { ticker: "MPLX", name: "MPLX LP" },
  { ticker: "PAA", name: "Plains All American Pipeline LP" },
  { ticker: "ADP", name: "Automatic Data Processing Inc." },
  { ticker: "PAYX", name: "Paychex Inc." },
  { ticker: "FIS", name: "Fidelity National Information Services Inc." },
  { ticker: "FISV", name: "Fiserv Inc." },
  { ticker: "ROP", name: "Roper Technologies Inc." },
  { ticker: "ITW", name: "Illinois Tool Works Inc." },
  { ticker: "EMR", name: "Emerson Electric Co." },
  { ticker: "ETN", name: "Eaton Corp. plc" },
  { ticker: "PH", name: "Parker Hannifin Corp." },
  { ticker: "CMI", name: "Cummins Inc." },
  { ticker: "GD", name: "General Dynamics Corp." },
  { ticker: "LHX", name: "L3Harris Technologies Inc." },
  { ticker: "WM", name: "Waste Management Inc." },
  { ticker: "RSG", name: "Republic Services Inc." },
  { ticker: "ECL", name: "Ecolab Inc." },
  { ticker: "LIN", name: "Linde plc" },
  { ticker: "APD", name: "Air Products and Chemicals Inc." },
  { ticker: "SHW", name: "Sherwin-Williams Co." },
  { ticker: "NEM", name: "Newmont Corp." },
  { ticker: "FCX", name: "Freeport-McMoRan Inc." },
  { ticker: "DOW", name: "Dow Inc." },
  { ticker: "DD", name: "DuPont de Nemours Inc." },
  { ticker: "LYB", name: "LyondellBasell Industries N.V." },
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF" },
  { ticker: "QQQ", name: "Invesco QQQ Trust" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF" },
  { ticker: "VXUS", name: "Vanguard Total International Stock ETF" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF" },
  { ticker: "VIG", name: "Vanguard Dividend Appreciation ETF" },
  { ticker: "DGRO", name: "iShares Core Dividend Growth ETF" },
  { ticker: "HDV", name: "iShares Core High Dividend ETF" },
  { ticker: "SPYD", name: "SPDR Portfolio S&P 500 High Dividend ETF" },
  { ticker: "SPHD", name: "Invesco S&P 500 High Div Low Volatility ETF" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium Income ETF" },
  { ticker: "QYLD", name: "Global X NASDAQ 100 Covered Call ETF" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund" },
  { ticker: "XLI", name: "Industrial Select Sector SPDR Fund" },
  { ticker: "XLY", name: "Consumer Discretionary Select Sector SPDR Fund" },
  { ticker: "XLP", name: "Consumer Staples Select Sector SPDR Fund" },
  { ticker: "XLU", name: "Utilities Select Sector SPDR Fund" },
  { ticker: "XLB", name: "Materials Select Sector SPDR Fund" },
  { ticker: "XLRE", name: "Real Estate Select Sector SPDR Fund" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF" },
  { ticker: "GLD", name: "SPDR Gold Shares" },
  { ticker: "SLV", name: "iShares Silver Trust" },
];
